### ISSUE TITLE
Hey there contributors 👋💖

### ISSUE THREAD

**Issue by rozeappletree** [gov-ai/ocr#1]
Thankyou for showing interest in this project 🚀👩‍🚀

We will be building an end-to-end platform for invoice OCR recognition. The main problem that we will be trying to solve is *recognition and detection of key-value pairs from invoices*. 
 
> 💡 We will be solving a non-trivial problem of inter-relating the text content in the invoices into key-value pairs.
> ⭐Along with it we will be doing detection and recognition of text characters as well !!
> 🚀 This will be machine learning + engineering project. A lot of engineering.

![image](https://user-images.githubusercontent.com/45640029/136219492-3a5bcc68-6321-4f1e-b0ab-6c9c5ac64d87.png)

Broadly discussing, we will build:

1. **Data annotation page:** We will be using labelstudio ✨
2. **Frontend:** For uploading the annotated dataset and for making prediction on new images.  🤷‍♂️
3. **Backend:** Write some endpoints and job queues. Mostly python stack 🐍
4. **Machine Learning:** We will use state-of-the-art model written in pytorch. 🙃

So, final result is as follows:

- User annotates data in data annotation page. Then downloads the annotated data. (we already have annotated data)
- Uploads data in frontend and clicks on start training. (This data will be added to a job queue) And will be informed when training is complete.
- Once notified, the user will open the inference page where predictions happen on unseen image/dataset

---

#### 1. Who is this project for? 🙄🙄🙄

- You are willing to build industry-ready project with other developers for resume or learning or any other purposes.
- You are a part of some company/organisation who is trying to solve this same problem.
- You want to start with open-source.
- You want to get your hands dirty with ML / Frontend / Backend

#### 2. What are requirements for this project? 😵🥴

- You definitely need to be proficient in either python or javascript. 
- You should know how to use github.

#### 3. Will you be payed during the project? 🤑💰

This is just like any other open-source project. Contribute only out of interest. Contributors will not be provided with any stipend.

#### 4. What is in it for me (i.e @INF800)?  🤓⚡

I am planning to build series of industry-ready open-source projects and guide some people along the way if possible. I am an engineer at heart and love building intelligent software. This is my way of democratizing machine learning. Along the way, other experienced people will join as well.

#### 5. How will project proceed and what will be the medium of communication? ⚠

Please read this section carefully. 

- On 10th Oct 2021 (Sunday) we will be having an interactive session over google meet / zoom. We will introduce ourselves and kick-off the project. We will meet once every {TBD} days.
- We will primarily discuss using github issues. You will be notified for every message over mail.
- We will follow agile methodology. A series of issues will be opened in project kanban board. You can send PR to any issue you think you are comfortable with. (we will discuss more in our introductory call)

**Comment by rozeappletree** [comment]
**Meeting link:** https://meet.google.com/aoc-zznh-xca
**Date:** 10th OCT 2021
**Time:** ~~11AM~~ 07:30 PM IST

Please join the meeting link on above mentioned date and time. 

Feel free to raise your queries here in comments and don't forget to introduce yourselves!! 😊

**Comment by rozeappletree** [comment]
**Fellow contributors: 😎🤩🙌**

Aashi Agarwal @Code-With-aashi
Abhishek Shyam @groom115
Amisha Purswani @Amisha-here
Ashish Ranjan @ashishrjn
Ayoub Oukrirou @Oukrirou
Barsha Singh @BarshaSingh
Diksha Bhati @dikshabhati1
Harsh Sheth @shetharsh24
Mahendra Kumar @kumar-mahendra
Priyanka Kumari @anshuedu28
Puneet Kaur @puneetkaur2929
Roshan Shafiha @roshanshafiha
Sukhseerat Kaur @Sukhseerat-Kaur
Shubhankit Chowdhury @shubhankit123
Swastika Singh @Swas2103
Tejas Patil @patil-tejas
Uttkarsh Singh @loneWarrior581
Vipul Anand @vipul818
Vaibhav Arora @vaibhavarora102


**Volunteer mentors: 😍⚡**

Vivekkumar Javiya @Codewithvk
Vijay Anand @VijayAnand-B 

Please let me know if your names are missing.

**Comment by vaibhavarora102** [comment]
Hey everyone 
Vaibhav Arora this side
Currently pursuing bachelor in Computer science, Former Machine learning intern at Eduwaive, and active in various communities and community roles
Looking forward to the integration of ML and web app and also deploying the web app.

**Comment by vipul818** [comment]
Hello everyone
I am Vipul Anand. I am in the 3rd year of B.Tech in Computer science and engineering, Haldia Institute of Technology. I am interested in ML and Data science. Excited for learning and implementing new things.

**Comment by kumar-mahendra** [comment]
Hey Everyone ,
I am Mahendra Kumar, Student of Mathematics& Computing  at IIT Goa. I am here to learn and increase my skillset + making a project which I can be proud of and showcase in my resume. Happy to be part of this community. 

Happy learning to all✌️

**Comment by Roshanshafiha** [comment]
Hi everyone ,
I am Shafiha , a bioinformatician by profession and I would like to learn new skills and specialize myself in other fields apart from science as well so that's why I am here. Great to meet you all.

**Comment by loneWarrior581** [comment]
Hey everyone, 
I am Uttkarsh a 3rd year undergraduate student. I love to build , and learn different tech on the go. I am here to extend the width on my learning via this project , build great software and moreover be a part of a community. Happy to meet you all 🤗

**Comment by shetharsh24** [comment]
Hello Everyone,

Harsh here. I am a Mechanical Engineer by profession and while working in
my domain, I got to know how data can impact your business and since then I
have started learning things my own.

Looking forward to working on this project with all you people and gain
knowledge!

I'd love to connect with you all through LinkedIn as well.

LinkedIn profile:
https://www.linkedin.com/in/shetharsh24

Regards,
Harsh S

**Comment by Swas2103** [comment]
Hello all,
I am Swastika, a 2nd year management student, specialising in Business
Analytics. I love to solve, code and decode problems while learning
different technologies on the go. I am here in hopes to collaborate and
contribute with all of you to build a great software.

Happy to meet you all

**Comment by Code-With-aashi** [comment]
Hello All. 

I am Aashi Agarwal. 

I am 2021 passed out btech CSE. I recently joined a company as a Jr. Data scientist. 

But i love to code, meeting new people. 

I am here to collaborate with you all and to learn amazing things from this collaboration.

**Comment by Amisha-here** [comment]
Hello everyone, 
I am Amisha Purswani, currently in my pre-final year studying CSE.  Here to increase my skill-set and 
looking forward to working on this project with you all and to have great learning experience. 
Happy to meet you all

**Comment by dikshabhati1** [comment]
Hello everyone,
I am Diksha Bhati currently in third year. I am here to learn more about open source contributions. I have worked on so many project and deployed some ml models on azure. Really excited to wok with you all

**Comment by ashishrjn** [comment]
Hello everyone,
I'm Ashish Ranjan currently final year student . Here to enhance my technical skills and would love to work with u all .
Great to meet u all.
my LinkedIn profile :- www.linkedin.com/in/ashishrjn

**Comment by BarshaSingh** [comment]
Hello everyone!!
I am Barsha Singh persuing MCA and also working as an Android developer..I am here to enhance my technical skills and looking forward to working with you all on this great project.
You can also connect with me on LinkedIn
https://www.linkedin.com/in/barsha-singh-77b652176

**Comment by rozeappletree** [comment]
Kind attention please everyone.

As @shetharsh24 has mentioned, would you be interested in having discord / telegram / slack / whatsapp group for quick communication?

Please **react to this comment with emoji** for voting each. (Reactions are not possible over email. You can react to comment from github page only [link here](https://github.com/gov-ai/ocr/issues/1#issuecomment-937549341))

🚀 Telegram
😄 WhatsApp
🎉 Discord
💗 Slack
👍  No need for any of the above

**Comment by rozeappletree** [comment]
Here is the link to whatsapp group: https://chat.whatsapp.com/GrvEqjhaWygD1Qmd5AT5vQ

**Comment by groom115** [comment]
Hello Everyone ,Myself Abhishek Shyam prefinal year undergrad at NIT silchar.I very interested in coding,ML,Dl etc . so excited to explore more here.

**Comment by puneetkaur2929** [comment]
Hello Everyone! 
Myself Puneet Kaur , I ' m pre final year under graduate student. 
I am here to relish the experience of working in real-time project. 
Looking forward for enriching learning experience. ✌🏻

**Comment by rozeappletree** [comment]
> **Meeting link:** https://meet.google.com/aoc-zznh-xca **Date:** 10th OCT 2021 **Time:** ~11AM~ 07:30 PM IST
> 
> Please join the meeting link on above mentioned date and time.
> 
> Feel free to raise your queries here in comments and don't forget to introduce yourselves!! 😊

Update: changed the timing

**Comment by Sukhseerat-Kaur** [comment]
Hey everyone!
Myself Sukhseerat Kaur, a 3rd year B. Tech. CSE student.
I took this opportunity to increase the band width of my skills and have the experience of making a real world project.
Looking forward to have a great learning.

**Comment by VijayAnand-B** [comment]
Hi guys! Feeling intimidated reading all the stellar introductions and experience of the people before me👆🏻but here goes mine. 
This is Vijay Anand. I am pursuing 3rd year Engineering. I have worked as Computer Vision intern for few months and am here to build a great product along with you guys. Lets rock together🥳😎🔥

**Comment by anshuedu28** [comment]
Hi everyone 😊
This is Priyanka Kumari
Batch 2021 passout
Currently working as a Data analyst.
I believe in the power of good community and learning together. Found this project very interesting and  hope to learn more.
Thanks @INF800 for this great opportunity 😊

You can add me on Linkedin-
https://www.linkedin.com/in/priyanka-kumari-bb3747195/. 🌼

**Comment by patil-tejas** [comment]
Hello Everyone, 
I am 2020 batch passout CSE.
Wanted to contribute towards some ML project and get some insight.
This project looked very interesting. Looking forward to work with you all.

**Comment by shubhanksargam** [comment]
Hey everyone!!
Shubhank here from SRMIST KTR. 
Currently in my prefinal year.
Really looking forward to contributing in this project:fire:🔥 
My linkedin: https://www.linkedin.com/in/shubhanks/

**Comment by rozeappletree** [comment]
Kind attention everyone 🤯

I have bootstrapped a [starter repo](https://github.com/gov-ai/thinking) for our OCR project. We will be moving to that repo and doing development there. Unfortunately I couldn't add front-end webapp and postgres db. Will add them soon. Try to go through the repo if possible. Even if you don't understand the repo it is okay! And if you do, feel free to send PR to postgres db, pgadmin and a simple react front-end app. We will talk more about it in today's 7:30pm call. Meanwhile I will try to open up series of issues that all of us can work on.

Looking forward to meet you all :D
